spring:
  datasource:
    url: url="jdbc:mariadb://localhost:3306/user_jwt"
    username: root
    password: jvman19
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
